apiVersion: v1
kind: ConfigMap
metadata:
  name: tms-config
  namespace: tms
data:
  MYSQL_DB: "tms_db"
  MYSQL_USER: "tms_user"
  REDIS_HOST: "redis-service"
  DB_HOST: "mysql-service"
  JWT_ACCESS_TOKEN_EXPIRES: "86400"
  DB_NAME: "tma"
  SQLALCHEMY_TRACK_MODIFICATIONS: "False"
  CELERY_BROKER_URL: "redis://redis-service:6379/0"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/0"
  REDIS_URL: "redis://redis-service:6379/0"
  CACHE_TYPE: "RedisCache"
  CACHE_REDIS_URL: "redis://redis-service:6379/0"
  CACHE_DEFAULT_TIMEOUT: "300"
  MAIL_SERVER: "smtp.gmail.com"
  MAIL_PORT: "587"
  MAIL_USE_TLS: "True"
  MAIL_USERNAME: "21f2000873@ds.study.iitm.ac.in"
  MAIL_DEFAULT_SENDER: "noreply@trekking.com"


